
# STATEMENT OF NON-PLAGIARISM

# I hereby declare that all information in this assignment has been obtained and presented in accordance with academic rules and ethical conduct and the work I am submitting in this document, except where I have indicated, is my own work.

# Student Number: 19307361
# Student Name: Joseph Libasora

# src directory makefile
# This makefile is just for ease of use and just calls the makefile inside `/bin`

build:
	$(MAKE) -C ../bin build

clean:
	$(MAKE) -C ../bin clean

run:
	$(MAKE) -C ../bin run

.PHONY: build clean run
